# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 02:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snap', models.FileField(blank=True, null=True, upload_to='Event/%Y/%m/%d')),
                ('eventtype', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_event', models.DateTimeField(default=False)),
                ('dresscode', models.BooleanField(default=False)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=400)),
                ('place', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
