# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='zip_Code',
            field=models.CharField(default=datetime.datetime(2016, 2, 28, 17, 21, 42, 322186, tzinfo=utc), max_length=6),
            preserve_default=False,
        ),
    ]
