# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 28, 19, 2, 9, 414723)),
        ),
    ]
