# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 04:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160227_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 29, 4, 11, 49, 306430)),
        ),
    ]
