# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160228_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 29, 17, 28, 43, 975783)),
        ),
    ]
