# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160228_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 31, 16, 16, 59, 116730)),
        ),
    ]
