# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20160330_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 30, 12, 52, 43, 178245)),
        ),
    ]
