# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20160331_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 8, 12, 39, 30, 358386)),
        ),
    ]
