# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20160408_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 8, 12, 41, 48, 581574)),
        ),
    ]
